class Types::HourlyDataType < Types::BaseObject
  field :time, Int, null: true, hash_key: 'time'
  field :summary, String, null: true, hash_key: 'summary'
  field :icon, String, null: true, hash_key: 'icon'
  field :precipIntensity, Float, null: true, hash_key: 'precipIntensity'
  field :precipProbability, Float, null: true, hash_key: 'precipProbability'
  field :precipType, String, null: true, hash_key: 'precipType'
  field :temperature, Float, null: true, hash_key: 'temperature'
  field :apparentTemperature, Float, null: true, hash_key: 'apparentTemperature'
  field :dewPoint, Float, null: true, hash_key: 'dewPoint'
  field :humidity, Float, null: true, hash_key: 'humidity'
  field :pressure, Float, null: true, hash_key: 'pressure'
  field :windSpeed, Float, null: true, hash_key: 'windSpeed'
  field :windGust, Float, null: true, hash_key: 'windGust'
  field :windBearing, Float, null: true, hash_key: 'windBearing'
  field :cloudCover, Float, null: true, hash_key: 'cloudCover'
  field :uvIndex, Int, null: true, hash_key: 'uvIndex'
  field :visibility, Float, null: true, hash_key: 'visibility'
  field :ozone, Float, null: true, hash_key: 'ozone'
end
